- name: Report deploy to Raygun
  block:
    - name: Report Deploy to Raygun
      uri:
        url: "https://app.raygun.com/deployments?authToken={{ raygun_auth_token }}"
        body_format: json
        method: POST
        body:
          apiKey: "{{ raygun_api_key }}"
          version: "{{ application }}-{{ version }}"
          comment: "Deployed with ansible config: {{ config_version }}"
          scmIdentifier: "{{ version }}"
          scmType: GitHub
      when: raygun_api_key is defined and (raygun_enabled|default(True)|bool)
      register: raygun
      no_log: "{{ not(unsafe_show_logs|bool) }}"
  rescue:
    - name: Explain raygun failure
      fail:
        msg: "Report deployment to raygun failed with status code '{{ raygun.status }}': {{ raygun.msg }}"
      when: raygun.failed

- name: Report deploy to Grafana
  grafana_annotations:
    url: "{{ grafana_url }}/api/annotations"
    tstamp: "{{ deployment_start_time }}"
    end_tstamp: "{{ deployment_end_time }}"
    tags:
      - deploy
      - namespace:{{ kube_resource_namespace }}
      - app:{{ kube_resource_name }}
    text: "Deployment {{ kube_resource_name }} {{ version }} {{ config_version }}"
    token: "{{ grafana_api_token }}"
  when: grafana_api_token is defined
  failed_when: false

- name: Report deploy to datadog
  community.general.datadog_event:
    title: >-
      Deployment of {{ application }} {{ version }} to {{ env }}
      {{ 'succeeded' if deploy_success else 'failed' }}
    text: >-
      Deployment of {{ application }} {{ version }} to {{ env }}
      {{ 'succeeded' if deploy_success else 'failed' }}
    api_key: "{{ datadog_api_key }}"
    app_key: "{{ datadog_app_key }}"
    tags:
      - type:deployment
      - version:{{ version }}
      - application:{{ application }}
      - environment:{{ env }}
      - namespace:{{ kube_resource_namespace }}
      - config:{{ config_version }}
      - changed:{{ resources_changed | str | lower }}
    alert_type: "{{ 'info' if deploy_success else 'error' }}"
  when: datadog_api_key is defined and datadog_app_key is defined
  failed_when: false
