- name: Report deploy to Grafana
  grafana_annotations:
    url: "{{ grafana_url }}/api/annotations"
    tstamp: "{{ deployment_start_time }}"
    end_tstamp: "{{ deployment_end_time }}"
    tags:
      - deploy
      - namespace:{{ kube_resource_namespace }}
      - app:{{ kube_resource_name }}
    text: "Deployment {{ kube_resource_name }} {{ version }} {{ config_version }}"
    token: "{{ grafana_api_token }}"
  when: grafana_api_token is defined
  failed_when: false
  changed_when: false

- name: Report deploy to datadog
  datadog_event:
    title: >-
      Deployment of {{ application }} {{ version }} to {{ instance }} {{ env }}
      {{ 'succeeded' if deploy_success else 'failed' }}
    text: >-
      Deployment of {{ application }} {{ version }} to {{ instance }} {{ env }}
      {{ 'succeeded' if deploy_success else 'failed' }}
    api_key: "{{ datadog_api_key }}"
    app_key: "{{ datadog_app_key }}"
    tags:
      - application:{{ application }}
      - changed:{{ resources_changed | string | lower }}
      - cluster:{{ kube_cluster_name }}
      - config:{{ config_version }}
      - duration:{{ (end_time|int - start_time|int) * 1000000000 }}
      - env:{{ env }}
      - environment:{{ env }}
      - finished:{{ (end_time|int) * 1000 }}
      - instance:{{ instance }}
      - namespace:{{ kube_resource_namespace }}
      - service:{{ application }}
      - started:{{ start_time|int * 1000 }}
      - success:{{ deploy_success | string | lower }}
      - type:deployment
      - version:{{ version }}
    alert_type: "{{ 'info' if deploy_success else 'error' }}"
  when: datadog_api_key is defined and datadog_app_key is defined
  failed_when: false
  changed_when: false
